# Dependabot configuration:
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - # Maintain dependencies for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "maven"
      - "dependabot"
    reviewers:
      - "MakeMeMonad"
    groups:
      maven-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "gradle"
      - "dependabot"
    reviewers:
      - "MakeMeMonad"
    groups:
      gradle-dependencies:
        patterns:
          - "*"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
      - "dependabot"
    reviewers:
      - "MakeMeMonad"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"